### PR TITLE
Typo fix in Bitcoin package

### PR DESCRIPTION
**Pull request by ghststmkls**
(Forwarded from previous PR to Master.)

Fixed references to Ripple and Ethereum that did not seem to fit Bitcoin's branch. 

-GSM

### CODE REVIEW

**Comment by alexchiriac** [comment]
Hi! Thank you very much for your contribution! Nice catch on the typos!

We update our documentation automatically using the JSDoc annotations in the actual class files. These updates to the README will be applied now, but the next time the Documentation is generated, your changes would be overwritten.

Would you like to update your PR to include the changes to the JSDoc annotations inside the Bitcoin.ts file? Alternatively, we will do that on our side!

Thanks again!

**Comment by najla-quant** [comment]
I think I've already added these typos in the last release.
@lukerQuant This PR is not the same you've sent to me ?

**Comment by lukerQuant** [comment]
Ok, if you have already made the changes in another branch then we can close it - but did you make the change in the file Alex mentioned or just the read me? I forgot about that difference previously to be fair

**Comment by najla-quant** [comment]
It was this one https://github.com/quantnetwork/overledger-sdk-javascript/pull/106.
I think they are the same typos

**Comment by alexchiriac** [comment]
Yep, they're the same, he closed the previous PR because it was to merge straight to 'master' rather than 'develop'. But the changes still need to be added in, as we can see those typos are still there in the develop branch:

https://github.com/quantnetwork/overledger-sdk-javascript/blob/95c70c230e2ef7861baf738806bdcdec8af58acd/packages/overledger-dlt-bitcoin/src/Bitcoin.ts#L54
https://github.com/quantnetwork/overledger-sdk-javascript/blob/95c70c230e2ef7861baf738806bdcdec8af58acd/packages/overledger-dlt-bitcoin/src/Bitcoin.ts#L158
https://github.com/quantnetwork/overledger-sdk-javascript/blob/95c70c230e2ef7861baf738806bdcdec8af58acd/packages/overledger-dlt-bitcoin/src/Bitcoin.ts#L86

Of course, once these are fixed in the Bitcoin.ts file, we need to re-generate the documentation :)

**Comment by najla-quant** [comment]
Yes, right. I changed only the read.me from the PR #106

**Comment by lukerQuant** [comment]
Closing this as the typo changes were added in a previous branch. Thank you @ghststmkls for highlighting them

**Pull request closed without merging**
