### PR TITLE
Feature/ch13645/add xrp atomic swaps and trust lines to corda and hlf

### PR DESCRIPTION
**Pull request by lukerQuant**
This branch:

- Added Hyperledger Fabric package to the SDK
- Added Corda package to the SDK
- Merged our previous work on XRP atomic swaps & trustlines into OVL standard form
- Redefined Account in a more standard form
- Provided the method to call node specific resources in a generic ways (overledgerCore.callNodeResource). First use of it is for the invokeWorkflow on Corda node, but other node specific resources (e.g. estimateFee, subscribe, queryPeers,...) could be grouped under that moving forward if needed as we move towards making the SDK more lightweight. 

Note there are some switches on HLF or Corda currently but this will be smartened up going forward.

### CODE REVIEW

**Comment by lukerQuant** [comment]
I'm just adding a few people who may be interested in this pull request as optionally reviewers.

**Comment by lukerQuant** [comment]
Oh I added Najla & Myself to the SDK contributors but feel free to add yourselves Mahsa & Richard to the packages you contributed to if you feel like it :-)

**Comment by lukerQuant** [comment]
Last call for comments on this

**Review by najla-quant — APPROVED** [review]

**Comment by lukerQuant** [comment]
Adding Corda, Hyperledger Fabric and more XRP transaction types

**Pull request merged**
