### PR TITLE
Feature/ch8024/upgrade and fix win10

### PR DESCRIPTION
**Pull request by alexchiriac**

### CODE REVIEW

**Comment by lukerQuant** [comment]
Code seems fine.  Has anyone ran the scripts for normal txs and smart contract transactions?

**Review by kashif-quant — COMMENTED** [review]
Did you manage to run all these in your windows environment?

**Review by najla-quant — APPROVED** [review]

**Review by kashif-quant — COMMENTED** [review]
Also, going forward, maybe we should have a windows environment (possibly managed by devops) for these kinds of exercises?

**Comment by alexchiriac** [comment]
> Code seems fine. Has anyone ran the scripts for normal txs and smart contract transactions?

I did for the normal transactions, works okay, but not for the SC transactions. I also ran all the tests and they all passed.

**Comment by alexchiriac** [comment]
@lukerQuant @kashif-quant I ran the smart contract examples as well as the transaction examples and they all work as expected

**Review by lukerQuant — APPROVED** [review]

**Review by kashif-quant — APPROVED** [review]

**Pull request merged**
